name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    name: Release & Publish
    runs-on: ubuntu-latest
    concurrency: release
    environment: release

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4
        with:
          fetch-depth: 0

      - name: Python Semantic Release
        id: release
        uses: python-semantic-release/python-semantic-release@0dc72ac9058a62054a45f6344c83a423d7f906a8  # v9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78  # v7
        if: steps.release.outputs.released == 'true'
        with:
          python-version: "3.11"
          enable-cache: false

      - name: Build
        if: steps.release.outputs.released == 'true'
        run: uv build

      - name: Publish to PyPI
        if: steps.release.outputs.released == 'true'
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e  # release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
